using UnityEngine;

[CreateAssetMenu(fileName = "SoundFXSO", menuName = "Scriptable Objects/SoundSO")]
public class SoundFXSO : ScriptableObject
{
  [Header("Inscribed")]
  public AudioClip sound;

  public float pitchMin;
  public float pitchMax;
  
  
  [Header("Sound Detection")]
  [Tooltip("How large the Noise field generated by this sound will be")]
  public float noiseRadius;
  
  
}
