using UnityEngine;

[CreateAssetMenu(fileName = "SoundFXSO", menuName = "Scriptable Objects/SoundSO")]
public class SoundFXSO : ScriptableObject
{
  [Header("Inscribed")]
  public AudioClip sound;

  public GameObject vfx;
    
  [Range(-3f, 3f)]
  public float pitchMin = 1;
  [Range(-3f, 3f)]
  public float pitchMax = 1;
  [Range(0f, 3f)]
  public float volume = 1;
  
  [Header("Sound Detection")]
  [Tooltip("How large the Noise field generated by this sound will be")]
  public float noiseRadius;
  
  
}
